name: notifyme
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

# isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter

  # logging package 
  logger: ^1.4.0
  # stacked framework
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  # webscraping service  
  beautiful_soup_dart: ^0.3.0
  # admob
  # Notification
  flutter_local_notifications: ^17.2.2
  # crashanalytics
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  # webview
  webview_flutter: ^4.9.0 #only supports android and ios
  # firebase backend
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  # Icon package
  font_awesome_flutter: ^10.7.0
  # Functional programming
  fpdart: ^1.1.0
  # local database
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.0.15
  # Svg asset
  flutter_svg: ^2.0.10+1
  # Star rating package
  flutter_rating_stars: ^1.1.0
  # Animation
  show_up_animation: ^2.0.0
  # Audio service
  just_audio: ^0.9.41
  # File picker
  file_picker: ^8.1.3
  # Url launcher
  url_launcher: ^6.3.1
  # Google Admob
  google_mobile_ads: ^5.2.0
  # Group list
  # grouped_list: ^6.0.0
  # Toast service
  fluttertoast: ^8.2.8
  # Internationalisation 
  intl: ^0.19.0
  # Permission handlers
  permission_handler: ^11.3.1
  # Background service handler
  flutter_background_service: ^5.0.10
  # Screenutils
  flutter_screenutil: ^5.9.3


dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  isar_generator: any

flutter:
  assets:
    - assets/images/
    - assets/sounds/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
  
  uses-material-design: true
