name: notifyme
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter

  # logging package 
  logger: ^1.4.0
  # stacked framework
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  # webscraping service  
  beautiful_soup_dart: ^0.3.0
  # admob
  # Notification
  flutter_local_notifications: ^17.2.2
  # crashanalytics
  # webview
  # webview_flutter: ^4.9.0 #only supports android and ios
  flutter_inappwebview: ^6.0.0 # extends support to web too
  # firebase backend
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.3
  # Icon package
  font_awesome_flutter: ^10.7.0
  # Functional programming
  fpdart: ^1.1.0
  # local database
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.0.15


dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  isar_generator: *isar_version

flutter:
  uses-material-design: true
