// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP5lWkUzznrVF7Ix_P_YuBF7-cB7qh5Ro',
    appId: '1:298576900475:web:1f2d8cf392b91029430dde',
    messagingSenderId: '298576900475',
    projectId: 'notify-me-job-notifier',
    authDomain: 'notify-me-job-notifier.firebaseapp.com',
    storageBucket: 'notify-me-job-notifier.appspot.com',
    measurementId: 'G-41VQTWR6TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI-M_0x40bYKikdxurUwi-qkddbK6XQU4',
    appId: '1:298576900475:android:61f47cbf33d6d750430dde',
    messagingSenderId: '298576900475',
    projectId: 'notify-me-job-notifier',
    storageBucket: 'notify-me-job-notifier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYlV75JXnUDxEa0nTTfLcmq8mGI9k2Sq4',
    appId: '1:298576900475:ios:3c598655a95e5fb6430dde',
    messagingSenderId: '298576900475',
    projectId: 'notify-me-job-notifier',
    storageBucket: 'notify-me-job-notifier.appspot.com',
    iosBundleId: 'com.notifyme.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYlV75JXnUDxEa0nTTfLcmq8mGI9k2Sq4',
    appId: '1:298576900475:ios:3c598655a95e5fb6430dde',
    messagingSenderId: '298576900475',
    projectId: 'notify-me-job-notifier',
    storageBucket: 'notify-me-job-notifier.appspot.com',
    iosBundleId: 'com.notifyme.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP5lWkUzznrVF7Ix_P_YuBF7-cB7qh5Ro',
    appId: '1:298576900475:web:cfc93230749fd2a4430dde',
    messagingSenderId: '298576900475',
    projectId: 'notify-me-job-notifier',
    authDomain: 'notify-me-job-notifier.firebaseapp.com',
    storageBucket: 'notify-me-job-notifier.appspot.com',
    measurementId: 'G-NV3REGFC6C',
  );
}
